export default  APP_COLOR = {

    WHITE: "#FFFFFF",
    BLACK: "#000000",
    PRIMARY_COLOR :'#FC9797',
    LEFT_SECONDARY_COLOR :'#84D9E4',
    MIDDLE_SECONDARY_COLOR : "#B5F6FF",
    BACKGROUND_COLOR : '#FFDFDF'

}